package ydys.jinou.com.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ydys.jinou.com.model.bean.CacheBean;
import ydys.jinou.com.model.cache.CollectCacheBean;

import ydys.jinou.com.model.db.CacheBeanDao;
import ydys.jinou.com.model.db.CollectCacheBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheBeanDaoConfig;
    private final DaoConfig collectCacheBeanDaoConfig;

    private final CacheBeanDao cacheBeanDao;
    private final CollectCacheBeanDao collectCacheBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheBeanDaoConfig = daoConfigMap.get(CacheBeanDao.class).clone();
        cacheBeanDaoConfig.initIdentityScope(type);

        collectCacheBeanDaoConfig = daoConfigMap.get(CollectCacheBeanDao.class).clone();
        collectCacheBeanDaoConfig.initIdentityScope(type);

        cacheBeanDao = new CacheBeanDao(cacheBeanDaoConfig, this);
        collectCacheBeanDao = new CollectCacheBeanDao(collectCacheBeanDaoConfig, this);

        registerDao(CacheBean.class, cacheBeanDao);
        registerDao(CollectCacheBean.class, collectCacheBeanDao);
    }
    
    public void clear() {
        cacheBeanDaoConfig.clearIdentityScope();
        collectCacheBeanDaoConfig.clearIdentityScope();
    }

    public CacheBeanDao getCacheBeanDao() {
        return cacheBeanDao;
    }

    public CollectCacheBeanDao getCollectCacheBeanDao() {
        return collectCacheBeanDao;
    }

}
